export type SeedMatch = {
  id: string
  matchNumber: number
  round: string
  group: string
  homeTeam: string
  awayTeam: string
  homeSource: string | null
  awaySource: string | null
  venue: string
  startsAt: Date
}

type MatchRow = [
  matchNumber: number,
  round: string,
  group: string,
  homeTeam: string,
  awayTeam: string,
  venue: string,
  date: string,
  time: string,
  utcOffsetHours: number,
  homeSource?: string | null,
  awaySource?: string | null,
  id?: string,
]

function kickoff(date: string, time: string, utcOffsetHours: number) {
  const [year, month, day] = date.split('-').map(Number)
  const [hour, minute] = time.split(':').map(Number)

  return new Date(Date.UTC(year, month - 1, day, hour - utcOffsetHours, minute))
}

function groupMatch(
  matchNumber: number,
  group: string,
  homeTeam: string,
  awayTeam: string,
  venue: string,
  date: string,
  time: string,
  utcOffsetHours: number,
  id?: string,
): MatchRow {
  return [
    matchNumber,
    'Fase de grupos',
    `Grupo ${group}`,
    homeTeam,
    awayTeam,
    venue,
    date,
    time,
    utcOffsetHours,
    null,
    null,
    id,
  ]
}

function knockoutMatch(
  matchNumber: number,
  round: string,
  homeTeam: string,
  awayTeam: string,
  venue: string,
  date: string,
  time: string,
  utcOffsetHours: number,
  homeSource: string,
  awaySource: string,
): MatchRow {
  return [
    matchNumber,
    round,
    'Mata-mata',
    homeTeam,
    awayTeam,
    venue,
    date,
    time,
    utcOffsetHours,
    homeSource,
    awaySource,
  ]
}

const rows: MatchRow[] = [
  groupMatch(
    1,
    'A',
    'México',
    'África do Sul',
    'Estadio Azteca, Mexico City',
    '2026-06-11',
    '13:00',
    -6,
  ),
  groupMatch(
    2,
    'A',
    'Coreia do Sul',
    'Tchéquia',
    'Estadio Akron, Zapopan',
    '2026-06-11',
    '20:00',
    -6,
  ),
  groupMatch(
    3,
    'B',
    'Canadá',
    'Bósnia e Herzegovina',
    'BMO Field, Toronto',
    '2026-06-12',
    '15:00',
    -4,
  ),
  groupMatch(
    4,
    'D',
    'Estados Unidos',
    'Paraguai',
    'SoFi Stadium, Inglewood',
    '2026-06-12',
    '18:00',
    -7,
  ),
  groupMatch(
    5,
    'C',
    'Haiti',
    'Escócia',
    'Gillette Stadium, Foxborough',
    '2026-06-13',
    '21:00',
    -4,
    'group-c-haiti-scotland',
  ),
  groupMatch(
    6,
    'D',
    'Austrália',
    'Turquia',
    'BC Place, Vancouver',
    '2026-06-13',
    '21:00',
    -7,
  ),
  groupMatch(
    7,
    'C',
    'Brasil',
    'Marrocos',
    'MetLife Stadium, East Rutherford',
    '2026-06-13',
    '18:00',
    -4,
    'group-c-brazil-morocco',
  ),
  groupMatch(
    8,
    'B',
    'Catar',
    'Suíça',
    "Levi's Stadium, Santa Clara",
    '2026-06-13',
    '12:00',
    -7,
  ),
  groupMatch(
    9,
    'E',
    'Costa do Marfim',
    'Equador',
    'Lincoln Financial Field, Philadelphia',
    '2026-06-14',
    '19:00',
    -4,
  ),
  groupMatch(
    10,
    'E',
    'Alemanha',
    'Curaçao',
    'NRG Stadium, Houston',
    '2026-06-14',
    '12:00',
    -5,
  ),
  groupMatch(
    11,
    'F',
    'Países Baixos',
    'Japão',
    'AT&T Stadium, Arlington',
    '2026-06-14',
    '15:00',
    -5,
  ),
  groupMatch(
    12,
    'F',
    'Suécia',
    'Tunísia',
    'Estadio BBVA, Guadalupe',
    '2026-06-14',
    '20:00',
    -6,
  ),
  groupMatch(
    13,
    'H',
    'Arábia Saudita',
    'Uruguai',
    'Hard Rock Stadium, Miami Gardens',
    '2026-06-15',
    '18:00',
    -4,
  ),
  groupMatch(
    14,
    'H',
    'Espanha',
    'Cabo Verde',
    'Mercedes-Benz Stadium, Atlanta',
    '2026-06-15',
    '12:00',
    -4,
  ),
  groupMatch(
    15,
    'G',
    'Irã',
    'Nova Zelândia',
    'SoFi Stadium, Inglewood',
    '2026-06-15',
    '18:00',
    -7,
  ),
  groupMatch(
    16,
    'G',
    'Bélgica',
    'Egito',
    'Lumen Field, Seattle',
    '2026-06-15',
    '12:00',
    -7,
  ),
  groupMatch(
    17,
    'I',
    'França',
    'Senegal',
    'MetLife Stadium, East Rutherford',
    '2026-06-16',
    '15:00',
    -4,
  ),
  groupMatch(
    18,
    'I',
    'Iraque',
    'Noruega',
    'Gillette Stadium, Foxborough',
    '2026-06-16',
    '18:00',
    -4,
  ),
  groupMatch(
    19,
    'J',
    'Argentina',
    'Argélia',
    'Arrowhead Stadium, Kansas City',
    '2026-06-16',
    '20:00',
    -5,
  ),
  groupMatch(
    20,
    'J',
    'Áustria',
    'Jordânia',
    "Levi's Stadium, Santa Clara",
    '2026-06-16',
    '21:00',
    -7,
  ),
  groupMatch(
    21,
    'L',
    'Gana',
    'Panamá',
    'Toronto Stadium, Toronto',
    '2026-06-17',
    '19:00',
    -4,
  ),
  groupMatch(
    22,
    'L',
    'Inglaterra',
    'Croácia',
    'AT&T Stadium, Arlington',
    '2026-06-17',
    '15:00',
    -5,
  ),
  groupMatch(
    23,
    'K',
    'Portugal',
    'RD Congo',
    'NRG Stadium, Houston',
    '2026-06-17',
    '12:00',
    -5,
  ),
  groupMatch(
    24,
    'K',
    'Uzbequistão',
    'Colômbia',
    'Estadio Azteca, Mexico City',
    '2026-06-17',
    '20:00',
    -6,
  ),
  groupMatch(
    25,
    'A',
    'Tchéquia',
    'África do Sul',
    'Mercedes-Benz Stadium, Atlanta',
    '2026-06-18',
    '12:00',
    -4,
  ),
  groupMatch(
    26,
    'B',
    'Suíça',
    'Bósnia e Herzegovina',
    'SoFi Stadium, Inglewood',
    '2026-06-18',
    '12:00',
    -7,
  ),
  groupMatch(
    27,
    'B',
    'Canadá',
    'Catar',
    'BC Place, Vancouver',
    '2026-06-18',
    '15:00',
    -7,
  ),
  groupMatch(
    28,
    'A',
    'México',
    'Coreia do Sul',
    'Estadio Akron, Zapopan',
    '2026-06-18',
    '19:00',
    -6,
  ),
  groupMatch(
    29,
    'C',
    'Brasil',
    'Haiti',
    'Lincoln Financial Field, Philadelphia',
    '2026-06-19',
    '20:30',
    -4,
    'group-c-brazil-haiti',
  ),
  groupMatch(
    30,
    'C',
    'Escócia',
    'Marrocos',
    'Gillette Stadium, Foxborough',
    '2026-06-19',
    '18:00',
    -4,
    'group-c-scotland-morocco',
  ),
  groupMatch(
    31,
    'D',
    'Turquia',
    'Paraguai',
    "Levi's Stadium, Santa Clara",
    '2026-06-19',
    '20:00',
    -7,
  ),
  groupMatch(
    32,
    'D',
    'Estados Unidos',
    'Austrália',
    'Lumen Field, Seattle',
    '2026-06-19',
    '12:00',
    -7,
  ),
  groupMatch(
    33,
    'E',
    'Alemanha',
    'Costa do Marfim',
    'BMO Field, Toronto',
    '2026-06-20',
    '16:00',
    -4,
  ),
  groupMatch(
    34,
    'E',
    'Equador',
    'Curaçao',
    'Arrowhead Stadium, Kansas City',
    '2026-06-20',
    '19:00',
    -5,
  ),
  groupMatch(
    35,
    'F',
    'Países Baixos',
    'Suécia',
    'NRG Stadium, Houston',
    '2026-06-20',
    '12:00',
    -5,
  ),
  groupMatch(
    36,
    'F',
    'Tunísia',
    'Japão',
    'Estadio BBVA, Guadalupe',
    '2026-06-20',
    '22:00',
    -6,
  ),
  groupMatch(
    37,
    'H',
    'Uruguai',
    'Cabo Verde',
    'Hard Rock Stadium, Miami Gardens',
    '2026-06-21',
    '18:00',
    -4,
  ),
  groupMatch(
    38,
    'H',
    'Espanha',
    'Arábia Saudita',
    'Mercedes-Benz Stadium, Atlanta',
    '2026-06-21',
    '12:00',
    -4,
  ),
  groupMatch(
    39,
    'G',
    'Bélgica',
    'Irã',
    'SoFi Stadium, Inglewood',
    '2026-06-21',
    '12:00',
    -7,
  ),
  groupMatch(
    40,
    'G',
    'Nova Zelândia',
    'Egito',
    'BC Place, Vancouver',
    '2026-06-21',
    '18:00',
    -7,
  ),
  groupMatch(
    41,
    'I',
    'Noruega',
    'Senegal',
    'MetLife Stadium, East Rutherford',
    '2026-06-22',
    '20:00',
    -4,
  ),
  groupMatch(
    42,
    'I',
    'França',
    'Iraque',
    'Lincoln Financial Field, Philadelphia',
    '2026-06-22',
    '17:00',
    -4,
  ),
  groupMatch(
    43,
    'J',
    'Argentina',
    'Áustria',
    'AT&T Stadium, Arlington',
    '2026-06-22',
    '12:00',
    -5,
  ),
  groupMatch(
    44,
    'J',
    'Jordânia',
    'Argélia',
    "Levi's Stadium, Santa Clara",
    '2026-06-22',
    '20:00',
    -7,
  ),
  groupMatch(
    45,
    'L',
    'Inglaterra',
    'Gana',
    'Gillette Stadium, Foxborough',
    '2026-06-23',
    '16:00',
    -4,
  ),
  groupMatch(
    46,
    'L',
    'Panamá',
    'Croácia',
    'Toronto Stadium, Toronto',
    '2026-06-23',
    '19:00',
    -4,
  ),
  groupMatch(
    47,
    'K',
    'Portugal',
    'Uzbequistão',
    'NRG Stadium, Houston',
    '2026-06-23',
    '12:00',
    -5,
  ),
  groupMatch(
    48,
    'K',
    'Colômbia',
    'RD Congo',
    'Estadio Akron, Zapopan',
    '2026-06-23',
    '20:00',
    -6,
  ),
  groupMatch(
    49,
    'C',
    'Escócia',
    'Brasil',
    'Hard Rock Stadium, Miami Gardens',
    '2026-06-24',
    '18:00',
    -4,
    'group-c-scotland-brazil',
  ),
  groupMatch(
    50,
    'C',
    'Marrocos',
    'Haiti',
    'Mercedes-Benz Stadium, Atlanta',
    '2026-06-24',
    '18:00',
    -4,
    'group-c-morocco-haiti',
  ),
  groupMatch(
    51,
    'B',
    'Suíça',
    'Canadá',
    'BC Place, Vancouver',
    '2026-06-24',
    '12:00',
    -7,
  ),
  groupMatch(
    52,
    'B',
    'Bósnia e Herzegovina',
    'Catar',
    'Lumen Field, Seattle',
    '2026-06-24',
    '12:00',
    -7,
  ),
  groupMatch(
    53,
    'A',
    'Tchéquia',
    'México',
    'Estadio Azteca, Mexico City',
    '2026-06-24',
    '19:00',
    -6,
  ),
  groupMatch(
    54,
    'A',
    'África do Sul',
    'Coreia do Sul',
    'Estadio BBVA, Guadalupe',
    '2026-06-24',
    '19:00',
    -6,
  ),
  groupMatch(
    55,
    'E',
    'Curaçao',
    'Costa do Marfim',
    'Lincoln Financial Field, Philadelphia',
    '2026-06-25',
    '16:00',
    -4,
  ),
  groupMatch(
    56,
    'E',
    'Equador',
    'Alemanha',
    'MetLife Stadium, East Rutherford',
    '2026-06-25',
    '16:00',
    -4,
  ),
  groupMatch(
    57,
    'F',
    'Japão',
    'Suécia',
    'AT&T Stadium, Arlington',
    '2026-06-25',
    '18:00',
    -5,
  ),
  groupMatch(
    58,
    'F',
    'Tunísia',
    'Países Baixos',
    'Arrowhead Stadium, Kansas City',
    '2026-06-25',
    '18:00',
    -5,
  ),
  groupMatch(
    59,
    'D',
    'Turquia',
    'Estados Unidos',
    'SoFi Stadium, Inglewood',
    '2026-06-25',
    '19:00',
    -7,
  ),
  groupMatch(
    60,
    'D',
    'Paraguai',
    'Austrália',
    "Levi's Stadium, Santa Clara",
    '2026-06-25',
    '19:00',
    -7,
  ),
  groupMatch(
    61,
    'I',
    'Noruega',
    'França',
    'Gillette Stadium, Foxborough',
    '2026-06-26',
    '15:00',
    -4,
  ),
  groupMatch(
    62,
    'I',
    'Senegal',
    'Iraque',
    'BMO Field, Toronto',
    '2026-06-26',
    '15:00',
    -4,
  ),
  groupMatch(
    63,
    'G',
    'Egito',
    'Irã',
    'Lumen Field, Seattle',
    '2026-06-26',
    '20:00',
    -7,
  ),
  groupMatch(
    64,
    'G',
    'Nova Zelândia',
    'Bélgica',
    'BC Place, Vancouver',
    '2026-06-26',
    '20:00',
    -7,
  ),
  groupMatch(
    65,
    'H',
    'Cabo Verde',
    'Arábia Saudita',
    'NRG Stadium, Houston',
    '2026-06-26',
    '19:00',
    -5,
  ),
  groupMatch(
    66,
    'H',
    'Uruguai',
    'Espanha',
    'Estadio Akron, Zapopan',
    '2026-06-26',
    '18:00',
    -6,
  ),
  groupMatch(
    67,
    'L',
    'Panamá',
    'Inglaterra',
    'MetLife Stadium, East Rutherford',
    '2026-06-27',
    '17:00',
    -4,
  ),
  groupMatch(
    68,
    'L',
    'Croácia',
    'Gana',
    'Lincoln Financial Field, Philadelphia',
    '2026-06-27',
    '17:00',
    -4,
  ),
  groupMatch(
    69,
    'J',
    'Argélia',
    'Áustria',
    'Arrowhead Stadium, Kansas City',
    '2026-06-27',
    '21:00',
    -5,
  ),
  groupMatch(
    70,
    'J',
    'Jordânia',
    'Argentina',
    'AT&T Stadium, Arlington',
    '2026-06-27',
    '21:00',
    -5,
  ),
  groupMatch(
    71,
    'K',
    'Colômbia',
    'Portugal',
    'Hard Rock Stadium, Miami Gardens',
    '2026-06-27',
    '19:30',
    -4,
  ),
  groupMatch(
    72,
    'K',
    'RD Congo',
    'Uzbequistão',
    'Mercedes-Benz Stadium, Atlanta',
    '2026-06-27',
    '19:30',
    -4,
  ),
  knockoutMatch(
    73,
    '16 avos de final',
    '2º Grupo A',
    '2º Grupo B',
    'SoFi Stadium, Inglewood',
    '2026-06-28',
    '12:00',
    -7,
    '2A',
    '2B',
  ),
  knockoutMatch(
    74,
    '16 avos de final',
    '1º Grupo E',
    '3º Grupo A/B/C/D/F',
    'Gillette Stadium, Foxborough',
    '2026-06-29',
    '16:30',
    -4,
    '1E',
    '3A/B/C/D/F',
  ),
  knockoutMatch(
    75,
    '16 avos de final',
    '1º Grupo F',
    '2º Grupo C',
    'Estadio BBVA, Guadalupe',
    '2026-06-29',
    '19:00',
    -6,
    '1F',
    '2C',
  ),
  knockoutMatch(
    76,
    '16 avos de final',
    '1º Grupo C',
    '2º Grupo F',
    'NRG Stadium, Houston',
    '2026-06-29',
    '12:00',
    -5,
    '1C',
    '2F',
  ),
  knockoutMatch(
    77,
    '16 avos de final',
    '1º Grupo I',
    '3º Grupo C/D/F/G/H',
    'MetLife Stadium, East Rutherford',
    '2026-06-30',
    '17:00',
    -4,
    '1I',
    '3C/D/F/G/H',
  ),
  knockoutMatch(
    78,
    '16 avos de final',
    '2º Grupo E',
    '2º Grupo I',
    'AT&T Stadium, Arlington',
    '2026-06-30',
    '12:00',
    -5,
    '2E',
    '2I',
  ),
  knockoutMatch(
    79,
    '16 avos de final',
    '1º Grupo A',
    '3º Grupo C/E/F/H/I',
    'Estadio Azteca, Mexico City',
    '2026-06-30',
    '19:00',
    -6,
    '1A',
    '3C/E/F/H/I',
  ),
  knockoutMatch(
    80,
    '16 avos de final',
    '1º Grupo L',
    '3º Grupo E/H/I/J/K',
    'Mercedes-Benz Stadium, Atlanta',
    '2026-07-01',
    '12:00',
    -4,
    '1L',
    '3E/H/I/J/K',
  ),
  knockoutMatch(
    81,
    '16 avos de final',
    '1º Grupo D',
    '3º Grupo B/E/F/I/J',
    "Levi's Stadium, Santa Clara",
    '2026-07-01',
    '17:00',
    -7,
    '1D',
    '3B/E/F/I/J',
  ),
  knockoutMatch(
    82,
    '16 avos de final',
    '1º Grupo G',
    '3º Grupo A/E/H/I/J',
    'Lumen Field, Seattle',
    '2026-07-01',
    '13:00',
    -7,
    '1G',
    '3A/E/H/I/J',
  ),
  knockoutMatch(
    83,
    '16 avos de final',
    '2º Grupo K',
    '2º Grupo L',
    'BMO Field, Toronto',
    '2026-07-02',
    '19:00',
    -4,
    '2K',
    '2L',
  ),
  knockoutMatch(
    84,
    '16 avos de final',
    '1º Grupo H',
    '2º Grupo J',
    'SoFi Stadium, Inglewood',
    '2026-07-02',
    '12:00',
    -7,
    '1H',
    '2J',
  ),
  knockoutMatch(
    85,
    '16 avos de final',
    '1º Grupo B',
    '3º Grupo E/F/G/I/J',
    'BC Place, Vancouver',
    '2026-07-02',
    '20:00',
    -7,
    '1B',
    '3E/F/G/I/J',
  ),
  knockoutMatch(
    86,
    '16 avos de final',
    '1º Grupo J',
    '2º Grupo H',
    'Hard Rock Stadium, Miami Gardens',
    '2026-07-03',
    '18:00',
    -4,
    '1J',
    '2H',
  ),
  knockoutMatch(
    87,
    '16 avos de final',
    '1º Grupo K',
    '3º Grupo D/E/I/J/L',
    'Arrowhead Stadium, Kansas City',
    '2026-07-03',
    '20:30',
    -5,
    '1K',
    '3D/E/I/J/L',
  ),
  knockoutMatch(
    88,
    '16 avos de final',
    '2º Grupo D',
    '2º Grupo G',
    'AT&T Stadium, Arlington',
    '2026-07-03',
    '13:00',
    -5,
    '2D',
    '2G',
  ),
  knockoutMatch(
    89,
    'Oitavas de final',
    'Vencedor Jogo 74',
    'Vencedor Jogo 77',
    'Lincoln Financial Field, Philadelphia',
    '2026-07-04',
    '17:00',
    -4,
    'W74',
    'W77',
  ),
  knockoutMatch(
    90,
    'Oitavas de final',
    'Vencedor Jogo 73',
    'Vencedor Jogo 75',
    'NRG Stadium, Houston',
    '2026-07-04',
    '12:00',
    -5,
    'W73',
    'W75',
  ),
  knockoutMatch(
    91,
    'Oitavas de final',
    'Vencedor Jogo 76',
    'Vencedor Jogo 78',
    'MetLife Stadium, East Rutherford',
    '2026-07-05',
    '16:00',
    -4,
    'W76',
    'W78',
  ),
  knockoutMatch(
    92,
    'Oitavas de final',
    'Vencedor Jogo 79',
    'Vencedor Jogo 80',
    'Estadio Azteca, Mexico City',
    '2026-07-05',
    '18:00',
    -6,
    'W79',
    'W80',
  ),
  knockoutMatch(
    93,
    'Oitavas de final',
    'Vencedor Jogo 81',
    'Vencedor Jogo 82',
    'Lumen Field, Seattle',
    '2026-07-06',
    '17:00',
    -7,
    'W81',
    'W82',
  ),
  knockoutMatch(
    94,
    'Oitavas de final',
    'Vencedor Jogo 83',
    'Vencedor Jogo 84',
    'AT&T Stadium, Arlington',
    '2026-07-06',
    '14:00',
    -5,
    'W83',
    'W84',
  ),
  knockoutMatch(
    95,
    'Oitavas de final',
    'Vencedor Jogo 85',
    'Vencedor Jogo 87',
    'BC Place, Vancouver',
    '2026-07-07',
    '13:00',
    -7,
    'W85',
    'W87',
  ),
  knockoutMatch(
    96,
    'Oitavas de final',
    'Vencedor Jogo 86',
    'Vencedor Jogo 88',
    'Mercedes-Benz Stadium, Atlanta',
    '2026-07-07',
    '12:00',
    -4,
    'W86',
    'W88',
  ),
  knockoutMatch(
    97,
    'Quartas de final',
    'Vencedor Jogo 89',
    'Vencedor Jogo 90',
    'Gillette Stadium, Foxborough',
    '2026-07-09',
    '16:00',
    -4,
    'W89',
    'W90',
  ),
  knockoutMatch(
    98,
    'Quartas de final',
    'Vencedor Jogo 93',
    'Vencedor Jogo 94',
    'SoFi Stadium, Inglewood',
    '2026-07-10',
    '12:00',
    -7,
    'W93',
    'W94',
  ),
  knockoutMatch(
    99,
    'Quartas de final',
    'Vencedor Jogo 91',
    'Vencedor Jogo 92',
    'Hard Rock Stadium, Miami Gardens',
    '2026-07-11',
    '17:00',
    -4,
    'W91',
    'W92',
  ),
  knockoutMatch(
    100,
    'Quartas de final',
    'Vencedor Jogo 95',
    'Vencedor Jogo 96',
    'Arrowhead Stadium, Kansas City',
    '2026-07-11',
    '20:00',
    -5,
    'W95',
    'W96',
  ),
  knockoutMatch(
    101,
    'Semifinal',
    'Vencedor Jogo 97',
    'Vencedor Jogo 98',
    'AT&T Stadium, Arlington',
    '2026-07-14',
    '14:00',
    -5,
    'W97',
    'W98',
  ),
  knockoutMatch(
    102,
    'Semifinal',
    'Vencedor Jogo 99',
    'Vencedor Jogo 100',
    'Mercedes-Benz Stadium, Atlanta',
    '2026-07-15',
    '15:00',
    -4,
    'W99',
    'W100',
  ),
  knockoutMatch(
    103,
    'Disputa de 3º lugar',
    'Perdedor Jogo 101',
    'Perdedor Jogo 102',
    'Hard Rock Stadium, Miami Gardens',
    '2026-07-18',
    '17:00',
    -4,
    'L101',
    'L102',
  ),
  knockoutMatch(
    104,
    'Final',
    'Vencedor Jogo 101',
    'Vencedor Jogo 102',
    'MetLife Stadium, East Rutherford',
    '2026-07-19',
    '15:00',
    -4,
    'W101',
    'W102',
  ),
]

export const seedMatches: SeedMatch[] = rows.map(
  ([
    matchNumber,
    round,
    group,
    homeTeam,
    awayTeam,
    venue,
    date,
    time,
    utcOffsetHours,
    homeSource = null,
    awaySource = null,
    id,
  ]) => ({
    id: id ?? `match-${matchNumber}`,
    matchNumber,
    round,
    group,
    homeTeam,
    awayTeam,
    homeSource,
    awaySource,
    venue,
    startsAt: kickoff(date, time, utcOffsetHours),
  }),
)
